name:               OLE-Storage_Lite
abstract:           Read and write OLE storage files.
version:            0.16
version_from:       Storage_Lite.pm
installdirs:        site
requires:

distribution_type:  module
license:            perl
generated_by:       hand
